routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::auth();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {


    Route::get('dashboard',           ['as' => 'dashboard',                     'uses' => 'DashboardController@index']);
    Route::get('error',               ['as' => 'error',                         'uses' => 'DashboardController@error500']);

    /*
     * Users route
     */
    Route::get('users',               ['as' => 'users.index',                   'uses' => 'UserController@index']);
    Route::get('users/create',        ['as' => 'users.create',                  'uses' => 'UserController@create']);
    Route::post('users',              ['as' => 'users.store',                   'uses' => 'UserController@store']);
    Route::get('users/{id}',          ['as' => 'users.show',                    'uses' => 'UserController@show']);
    Route::get('users/{id}/edit',     ['as' => 'users.edit',                    'uses' => 'UserController@edit']);
    Route::post('users/{id}',         ['as' => 'users.update',                  'uses' => 'UserController@update']);
    Route::get('users/{id}/destroy',  ['as' => 'users.destroy',                 'uses' => 'UserController@destroy']);


    /*
    *Questions Route
    */

    Route::get('questions',               ['as' => 'questions.index',        'uses' => 'QuestionsController@index']);
    Route::get('questions/create',        ['as' => 'questions.create',       'uses' => 'QuestionsController@create']);
    Route::post('questions',              ['as' => 'questions.store',        'uses' => 'QuestionsController@store']);
    Route::get('questions/{id}',          ['as' => 'questions.show',         'uses' => 'QuestionsController@show']);
    Route::get('questions/{id}/edit',     ['as' => 'questions.edit',         'uses' => 'QuestionsController@edit']);
    Route::post('questions/{id}',         ['as' => 'questions.update',       'uses' => 'QuestionsController@update']);
    Route::get('questions/{id}/destroy',  ['as' => 'questions.destroy',      'uses' => 'QuestionsController@destroy']);

/*
 * form route
 */
    Route::get('forms',               ['as' => 'forms.index',               'uses' => 'FormsController@index']);
    Route::get('forms/create',        ['as' => 'forms.create',              'uses' => 'FormsController@create']);
    Route::post('forms',              ['as' => 'forms.store',               'uses' => 'FormsController@store']);
    Route::get('forms/get-form-html',['as' =>'forms.get-question-html',  'uses' => 'FormsController@getQuestionHtml']);
    Route::get('forms/{id}',          ['as' => 'forms.show',                'uses' => 'FormsController@show']);
    Route::get('forms/{id}/edit',     ['as' => 'forms.edit',                'uses' => 'FormsController@edit']);
    Route::post('forms/{id}',         ['as' => 'forms.update',              'uses' => 'FormsController@update']);
    Route::get('forms/{id}/destroy',  ['as' => 'forms.destroy',             'uses' => 'FormsController@destroy']);
    Route::get('forms/{id}/destroy',  ['as' => 'forms.destroy',             'uses' => 'FormsController@destroy']);


});

Route::group(['namespace' => 'Front\\'], function () {

    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);

    Route::post('form-submit', ['as' => 'front.form.submit', 'uses' => 'HomeController@formSubmit']);

    Route::get('forms/response',  ['as' => 'forms.response',             'uses' => 'HomeController@exportFormResponse']);




});

app/Http/Controllers/Admin/QuestionsController.php
<?php
namespace App\Http\Controllers\Admin;


use App\Http\Requests\Admin\Question\QuestionAddValidationRequest;
use App\Http\Requests\Admin\Question\QuestionEditValidation;
use App\Model\Question;
use DB;
use Illuminate\Http\Request;




class QuestionsController extends AdminBaseController
{
    protected $model;
    protected $base_route = 'admin.questions';
    protected $view_path = 'admin.questions';

    public function index(Request $request)
    {
        $data = [];
        $data['rows']=Question::all();

        return view(parent::loadDataToView($this->view_path.'.index'), [
            'data' => $data,

        ]);
    }

    public function create()
    {
        $data=[];

        $data['questions_type']=config('act360.form_notification.question.type');

        return view(parent::loadDataToView($this->view_path.'.add'),compact('data'));
    }

    public function store(QuestionAddValidationRequest $request)
    {
        $question = Question::create([
            'title' => $request->get('title'),
            'type' => $request->get('question-type'),
            'status' => $request->get('status'),
            'name' => $request->get('name'),
        ]);



        $request->session()->flash('curd_message', 'Question Added successfully.');
        return redirect()->route($this->base_route.'.index');


    }


    public function edit($id)
    {
        if (!$this->model = Question::find($id)) {
            return redirect()->route($this->error_route);
        }


        $data = [];
        $data['questions_type']=config('act360.form_notification.question.type');
        $data['row'] = $this->model;

        return view(parent::loadDataToView($this->view_path.'.edit'), [
            'data' => $data
        ]);

    }



    public function update(QuestionEditValidation $request, $id)
    {

        if (!$this->model = Question::find($id)) {
            dd('Invalid user id passed.');
        }

        $this->model->title = $request->get('title');
        $this->model->type = $request->get('question-type');
        $this->model->name = $request->get('name');
        $this->model->status = $request->get('status');

        $this->model->save();

        $request->session()->flash('curd_message', 'Questions updated successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function destroy(Request $request, $id)
    {
        if (!$this->model = Question::find($id)) {
            return redirect()->route($this->error_route);
        }
        $this->model->delete();

        $request->session()->flash('curd_message', 'Questions deleted successfully.');
        return redirect()->route($this->base_route.'.index');

    }




}

resources/views/admin/questions/add.blade.php
@extends('admin.common.layout')

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{{ route('admin.dashboard') }}">{{ trans('admin/dashboard/general.home') }}</a>
                </li>

                <li>
                    <a href="{{ route('admin.users.index') }}">{{ trans($trans_path.'manager') }}</a>
                </li>
                <li class="active">{{ trans($trans_path.'add-questions') }}</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="icon-search nav-search-icon"></i>
								</span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ trans($trans_path.'manager') }}
                    <small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'add-form') }}
                    </small>

                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    @include('admin.common.crud_message')

                    <form class="form-horizontal" role="form" action="{{ route($base_route.'.store') }}" method="POST">
                        {{ csrf_field() }}

                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'title') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> {{ trans($trans_path.'title') }} <span class="required-field">*</span> </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="title" value="{{ old('title') }}" placeholder="{{ trans($trans_path.'title') }}" class="col-xs-10 col-sm-5" />
                            </div>
                            {{ ViewHelper::showValidationMessage($errors, 'title') }}
                        </div>

                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'name') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Input Name <span class="required-field">*</span> </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="name" value="{{ old('name') }}" placeholder="Eg.Email" class="col-xs-10 col-sm-5" />
                            </div>
                            {{ ViewHelper::showValidationMessage($errors, 'title') }}
                        </div>


                        <div class="space-4"></div>


                        <div class=" form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> {{ trans($trans_path.'question-type') }} </label>

                            <div class="col-sm-4">
                                 <select name="question-type"  class="form-control col-xs-4 col-sm-5" >{{ old('question-type') }}>
                                     @foreach($data['questions_type'] as $key => $value)
                                 <option value="{{$key}}"> {{$value}} </option>
                                     @endforeach
                                 </select>
                            </div>

                        </div>

                        <div class="space-4"></div>

                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'status') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-5">{{ trans($trans_path.'status') }}</label>

                            <?php
                                $chk_1 = 'checked';
                                $chk_2 = '';

                                if (old('status') == 'inactive') {

                                    $chk_1 = '';
                                    $chk_2 = 'checked';

                                }


                            ?>


                            <div class="col-sm-9">
                                <div class="control-group">
                                    <div class="radio">
                                        <label>
                                            <input name="status" class="ace" type="radio" value="1" name="status" {{ $chk_1 }} >
                                            <span class="lbl"> {{ trans($trans_path.'active') }} </span>
                                        </label>
                                    </div>

                                    <div class="radio">
                                        <label>
                                            <input name="status" class="ace" type="radio" value="0" name="status" {{ $chk_2 }}>
                                            <span class="lbl"> {{ trans($trans_path.'inactive') }} </span>
                                        </label>
                                    </div>

                                </div>
                                {{ ViewHelper::showValidationMessage($errors, 'status') }}
                            </div>
                        </div>

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i>
                                    Submit
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="icon-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>

                    </form>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div><!-- /.main-content -->

    @endsection

resources/views/admin/questions/edit.blade.php
@extends('admin.common.layout')

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{{ route('admin.dashboard') }}">{{ trans('admin/dashboard/general.home') }}</a>
                </li>

                <li>
                    <a href="{{ route('admin.users.index') }}">{{ trans($trans_path.'manager') }}</a>
                </li>
                <li class="active">{{ trans($trans_path.'update-user') }}</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="icon-search nav-search-icon"></i>
								</span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ trans($trans_path.'manager') }}
                    <small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'update-form') }}
                    </small>

                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    @include('admin.common.crud_message')

                    <form class="form-horizontal" role="form" action="{{ route(ViewHelper::getAdminRoute('questions.update'), ['id' => $data['row']->id]) }}" method="POST">
                        {{ csrf_field() }}
                        <input type="hidden" name="question_id" value="{{ $data['row']->id }}">


                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'title') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> {{ trans($trans_path.'title') }} <span class="required-field">*</span> </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="title" value="{{$data['row']?$data['row']->title: old('title') }}" placeholder="{{ trans($trans_path.'title') }}" class="col-xs-10 col-sm-5" />
                            </div>
                            {{ ViewHelper::showValidationMessage($errors, 'title') }}
                        </div>

                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'name') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Input Name <span class="required-field">*</span> </label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="name" value="{{$data['row']?$data['row']->name: old('title') }}" placeholder="Eg.Email" class="col-xs-10 col-sm-5" />
                            </div>
                            {{ ViewHelper::showValidationMessage($errors, 'title') }}
                        </div>


                        <div class="space-4"></div>


                        <div class=" form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> {{ trans($trans_path.'question-type') }} </label>

                            <div class="col-sm-4">
                                <select name="question-type"  class="form-control col-xs-4 col-sm-5" >{{ old('question-type') }}>
                                    @foreach($data['questions_type'] as $key => $value)
                                        <option value="{{$key}}"> {{$value}} </option>
                                    @endforeach
                                </select>
                            </div>

                        </div>

                        <div class="space-4"></div>


                        <hr>








                        <div class="{{ ViewHelper::ShowValidationClass($errors, 'status') }} form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="form-field-5">{{ trans($trans_path.'status') }}</label>

                            <?php
                                $chk_1 = 'checked';
                                $chk_2 = '';

                                if ($data['row']->status == 0) {
                                    $chk_1 = '';
                                    $chk_2 = 'checked';
                                }

                                if (old('status')) {

                                    if (old('status') == 1) {

                                        $chk_1 = '';
                                        $chk_2 = 'checked';

                                    } else {

                                        $chk_1 = 'checked';
                                        $chk_2 = '';

                                    }



                                }


                            ?>


                            <div class="col-sm-9">
                                <div class="control-group">
                                    <div class="radio">
                                        <label>
                                            <input name="status" class="ace" type="radio" value="1" name="status" {{ $chk_1 }} >
                                            <span class="lbl"> {{ trans($trans_path.'active') }} </span>
                                        </label>
                                    </div>

                                    <div class="radio">
                                        <label>
                                            <input name="status" class="ace" type="radio" value="0" name="status" {{ $chk_2 }}>
                                            <span class="lbl"> {{ trans($trans_path.'inactive') }} </span>
                                        </label>
                                    </div>

                                </div>
                                {{ ViewHelper::showValidationMessage($errors, 'status') }}
                            </div>
                        </div>

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i>
                                    Submit
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="icon-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>

                    </form>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div><!-- /.main-content -->

    @endsection

resources/views/admin/questions/index.blade.php
@extends('admin.common.layout')


@section('page_specific_css')

    <style>

        .main-content {
            background-color: red;
        }


    </style>

@endsection

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{{ route('admin.dashboard') }}">{{ trans('admin/dashboard/general.home') }}</a>
                </li>

                <li>
                    <a href="{{ route('admin.users.index') }}">{{ trans($trans_path.'manager') }}</a>
                </li>
                <li class="active">{{ trans($trans_path.'list') }}</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off"/>
									<i class="icon-search nav-search-icon"></i>
								</span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ trans($trans_path.'manager') }}
                    <small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'list') }}
                    </small>

                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    @include('admin.common.crud_message')

                    <div class="row">
                        <div class="col-xs-12">
                            <div class="table-responsive">
                                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                                    <thead>

                                    <tr>
                                        <th> {{ trans($trans_path.'id') }}</th>
                                        <th> {{ trans($trans_path.'title') }}</th>
                                        <th> {{ trans($trans_path.'question-type') }}</th>

                                        <th>
                                            <i class="icon-time bigger-110 hidden-480"></i>
                                            {{ trans($trans_path.'created_at') }}
                                        </th>
                                        <th>{{ trans($trans_path.'status') }}</th>
                                        <th class="hidden-480"> {{ trans($trans_path.'action') }}</th>

                                    </tr>
                                    </thead>

                                    <tbody>

                                    @if (isset($data['rows']) && $data['rows']->count() > 0))
                                        @foreach($data['rows'] as $row)
                                            <tr>
                                                <td>{{ $row->id}}</td>
                                                <td>{{ $row->title }}</td>
                                                <td>{{ $row->type }}</td>
                                                <td>{{ $row->created_at }}</td>
                                                <td><span class="label label-sm label-{{ $row->status == 1?'success':'warning' }}">{{ $row->status == 1?'Active':'Inactive' }}</span></td>
                                                <td>
                                                    <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                                                        <a href="{{ route('admin.questions.edit', [ 'id' => $row->id ]) }}" class="btn btn-xs btn-info">
                                                            <i class="icon-edit bigger-120"></i>
                                                        </a>

                                                        <a href="{{ route('admin.questions.destroy', [ 'id' => $row->id ]) }}" class="btn btn-xs btn-danger bootbox-confirm">
                                                            <i class="icon-trash bigger-120"></i>
                                                        </a>

                                                    </div>

                                                </td>
                                            </tr>
                                        @endforeach

                                    @else

                                        <tr>
                                            <td colspan="7">No data found.</td>
                                        </tr>

                                    @endif

                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /span -->
                    </div><!-- /row -->

                    <div class="hr hr-18 dotted hr-double"></div>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div><!-- /.main-content -->

@endsection


@section('page_specific_script')

    <script>
        $(document).ready(function () {

            $('#search_btn').click(function () {

                var search_by = $('#search_by').val();
                var search_key = $('#search_key').val();

                var current_url = '{{ URL::current() }}';

                var redirect_url = current_url + '?search_by=' + search_by + '&search_key=' + search_key;
                location.href = redirect_url;

                // console.log(redirect_url);
            });


            $('#search_by').on('change', function () {
                if ($(this).val() == 'status') {
                    $('#search_by_hint').html('Possible keys are [ active / inactive ]').show();
                } else {
                    $('#search_by_hint').hide();
                }
            });


        });
    </script>

@endsection