routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::auth();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {


    Route::get('dashboard',           ['as' => 'dashboard',                     'uses' => 'DashboardController@index']);
    Route::get('error',               ['as' => 'error',                         'uses' => 'DashboardController@error500']);

    /*
     * Users route
     */
    Route::get('users',               ['as' => 'users.index',                   'uses' => 'UserController@index']);
    Route::get('users/create',        ['as' => 'users.create',                  'uses' => 'UserController@create']);
    Route::post('users',              ['as' => 'users.store',                   'uses' => 'UserController@store']);
    Route::get('users/{id}',          ['as' => 'users.show',                    'uses' => 'UserController@show']);
    Route::get('users/{id}/edit',     ['as' => 'users.edit',                    'uses' => 'UserController@edit']);
    Route::post('users/{id}',         ['as' => 'users.update',                  'uses' => 'UserController@update']);
    Route::get('users/{id}/destroy',  ['as' => 'users.destroy',                 'uses' => 'UserController@destroy']);


    /*
    *Questions Route
    */

    Route::get('questions',               ['as' => 'questions.index',        'uses' => 'QuestionsController@index']);
    Route::get('questions/create',        ['as' => 'questions.create',       'uses' => 'QuestionsController@create']);
    Route::post('questions',              ['as' => 'questions.store',        'uses' => 'QuestionsController@store']);
    Route::get('questions/{id}',          ['as' => 'questions.show',         'uses' => 'QuestionsController@show']);
    Route::get('questions/{id}/edit',     ['as' => 'questions.edit',         'uses' => 'QuestionsController@edit']);
    Route::post('questions/{id}',         ['as' => 'questions.update',       'uses' => 'QuestionsController@update']);
    Route::get('questions/{id}/destroy',  ['as' => 'questions.destroy',      'uses' => 'QuestionsController@destroy']);

/*
 * form route
 */
    Route::get('forms',               ['as' => 'forms.index',               'uses' => 'FormsController@index']);
    Route::get('forms/create',        ['as' => 'forms.create',              'uses' => 'FormsController@create']);
    Route::post('forms',              ['as' => 'forms.store',               'uses' => 'FormsController@store']);
    Route::get('forms/get-form-html',['as' =>'forms.get-question-html',  'uses' => 'FormsController@getQuestionHtml']);
    Route::get('forms/{id}',          ['as' => 'forms.show',                'uses' => 'FormsController@show']);
    Route::get('forms/{id}/edit',     ['as' => 'forms.edit',                'uses' => 'FormsController@edit']);
    Route::post('forms/{id}',         ['as' => 'forms.update',              'uses' => 'FormsController@update']);
    Route::get('forms/{id}/destroy',  ['as' => 'forms.destroy',             'uses' => 'FormsController@destroy']);
    Route::get('forms/{id}/destroy',  ['as' => 'forms.destroy',             'uses' => 'FormsController@destroy']);


});

Route::group(['namespace' => 'Front\\'], function () {

    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);

    Route::post('form-submit', ['as' => 'front.form.submit', 'uses' => 'HomeController@formSubmit']);

    Route::get('forms/response',  ['as' => 'forms.response',             'uses' => 'HomeController@exportFormResponse']);




});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','username', 'status', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function userDetails()
    {
        return $this->hasMany('App\Model\UserDetails', 'user_id');
    }

    /**
     * Set the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * Set the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function setStatusAttribute($value)
    {
        $this->attributes['status'] = $value == 'active'?1:0;
    }

}

app/Http/Controllers/Admin/UserController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\User\QuestionAddValidationRequest;
use App\Http\Requests\Admin\User\QuestionEditValidation;
use App\Http\Requests\Admin\User\UserAddValidationRequest;
use App\Model\UserDetails;
use App\User;
use DB;
use Illuminate\Http\Request;

class UserController extends AdminBaseController
{
    protected $model;
    protected $base_route = 'admin.users';
    protected $view_path = 'admin.user';

    public function index(Request $request)
    {
        $data = [];
        $data['rows'] = User::select(
            'users.id', 'users.username', 'users.email',
            'users.updated_at', 'users.status',
            'ud.first_name', 'ud.middle_name', 'ud.last_name',
            DB::raw('CONCAT(ud.first_name, " ", ud.middle_name, " ", ud.last_name) AS full_name')
            )
            ->leftJoin('user_details as ud', 'users.id', '=', 'ud.user_id')
            ->where(function($query) use ($request) {
                if ($request->has('search_by')) {
                    $query->where($this->getSearchBy($request->get('search_by')), 'like', '%'.$this->getSearchKey($request->get('search_by'), $request->get('search_key')).'%');
                }

            })
            ->paginate($this->pagination_limit);



        $search_params = [];
        if ($request->has('search_by')) {
            $search_params['search_by'] = $request->get('search_by');
            $search_params['search_key'] = $request->get('search_key');
        }

        return view(parent::loadDataToView($this->view_path.'.index'), [
            'data' => $data,
            'search' => $search_params
        ]);
    }

    public function create()
    {
        return view(parent::loadDataToView($this->view_path.'.add'));
    }

    public function store(UserAddValidationRequest $request)
    {

        $user = User::create([
            'username' => $request->has('username')?$request->get('username'):'-',
            'email' => $request->get('email'),
            'password' => $request->get('password'),
            'status' => $request->get('status'),
        ]);

        if ($user) {

            UserDetails::create([
                'user_id' => $user->id,
                'first_name' => $request->get('first-name'),
                'middle_name' => $request->get('middle-name'),
                'last_name' => $request->get('last-name'),
                'gender' => $request->get('gender'),
                'address' => $request->get('address'),
                'phone' => $request->get('phone'),
            ]);

            $role_id=DB::table('roles')->select('id')->where('name',$request->get('role'))->first();
             DB::table('role_users')->insert([
                'user_id'=>$user->id,
                'role_id'=>$role_id->id

            ]);

        }


        $request->session()->flash('curd_message', 'User Added successfully.');
        return redirect()->route($this->base_route.'.index');


    }


    public function edit($user_id)
    {
        if (!$this->model = User::find($user_id)) {
            return redirect()->route($this->error_route);
        }

        $data = [];
        $data['row'] = $this->model;
        $data['user_details'] = $this->model->userDetails()->first();

        return view(parent::loadDataToView($this->view_path.'.edit'), [
            'data' => $data
        ]);

    }



    public function update(QuestionEditValidation $request, $user_id)
    {

        if (!$this->model = User::find($user_id)) {
            dd('Invalid user id passed.');
        }

        $this->model->username = $request->get('username');
        $this->model->email = $request->get('email');
        $this->model->status = $request->get('status');
        $this->model->is_admin = 1;

        if ($request->get('password') !== '')
            $this->model->password = $request->get('password');

        $this->model->save();

        if ($this->userModel = UserDetails::where('user_id', $this->model->id)->find($request->get('user_detail_id'))) {

            $this->userModel->update([
                'id' => $this->userModel->id,
                'first_name' => $request->get('first-name'),
                'middle_name' => $request->get('middle-name'),
                'last_name' => $request->get('last-name'),
                'address' => $request->get('address'),
                'phone' => $request->get('phone'),
                'gender' => $request->get('gender'),
            ]);


        }

        $request->session()->flash('curd_message', 'User updated successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function destroy(Request $request, $user_id)
    {
        if (!$this->model = User::find($user_id)) {
            return redirect()->route($this->error_route);
        }

        if (auth()->user()->id == $user_id) {
            return redirect()->route($this->error_route);
        }

        UserDetails::where('user_id', $this->model->id)->delete();
        $this->model->delete();

        $request->session()->flash('curd_message', 'User deleted successfully.');
        return redirect()->route($this->base_route.'.index');

    }




    /**
     * Helper Methods
     */


    /**
     * Returns Search Key For User Search
     *
     * @param $search_by
     * @return string
     */
    protected function getSearchBy($search_by)
    {
        switch ($search_by) {

            case 'id':
                return 'users.id';
                break;

            case 'first_name':
                return 'ud.first_name';
                break;

            case 'username':
                return 'users.username';
                break;

            case 'email':
                return 'users.email';
                break;

            case 'status':
                return 'users.status';
                break;

            case 'created_at':
                return 'users.created_at';
                break;

            default:
                return 'id';
        }
    }

    /**
     * Returns Search Key For User Search
     *
     * @param $search_by
     * @param $search_key
     * @return int|string
     */
    protected function getSearchKey($search_by, $search_key)
    {
        switch ($search_by) {

            case 'id':
            case 'first_name':
            case 'username':
            case 'email':
            case 'created_at':
                return $search_key;
                break;

            case 'status':
                $status = strtolower($search_key);
                if ($status == 'active')
                    return 1;

                return 0;
                break;

            default:
                return '';
        }
    }

}

resources/views/admin/user/index.blade.php
@extends('admin.common.layout')


@section('page_specific_css')

    <style>

        .main-content {
            background-color: red;
        }


    </style>

@endsection

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{{ route('admin.dashboard') }}">{{ trans('admin/dashboard/general.home') }}</a>
                </li>

                <li>
                    <a href="{{ route('admin.users.index') }}">{{ trans($trans_path.'manager') }}</a>
                </li>
                <li class="active">{{ trans($trans_path.'list') }}</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off"/>
									<i class="icon-search nav-search-icon"></i>
								</span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ trans($trans_path.'manager') }}
                    <small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'list') }}
                    </small>

                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    @include('admin.common.crud_message')

                    <div class="row">
                        <div class="col-xs-12">
                            <div class="table-responsive">
                                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th colspan="5">
                                            <select name="search_by" id="search_by">
                                                <option value="id" {{ Request::get('search_by') == 'id'?'selected':'' }}>User Id</option>
                                                <option value="first_name" {{ Request::get('search_by') == 'first_name'?'selected':'' }}>First Name</option>
                                                <option value="username" {{ Request::get('search_by') == 'username'?'selected':'' }}>Name</option>
                                                <option value="email" {{ Request::get('search_by') == 'email'?'selected':'' }}>Email</option>
                                                <option value="status" {{ Request::get('search_by') == 'status'?'selected':'' }}>Status</option>
                                                <option value="created_at" {{ Request::get('search_by') == 'created_at'?'selected':'' }}>Created At</option>
                                            </select>
                                            <input type="text" name="search_key" id="search_key" value="{{ Request::get('search_key')?Request::get('search_key'):'' }}">
                                            <button id="search_btn" class="btn btn-xs btn-info">Search</button>
                                            <p id="search_by_hint" style="display: none;"></p>
                                        </th>
                                        <th colspan="2"></th>
                                    </tr>
                                    <tr>
                                        <th> {{ trans($trans_path.'id') }}</th>
                                        <th> {{ trans($trans_path.'name') }}</th>
                                        <th> {{ trans($trans_path.'username') }}</th>
                                        <th> {{ trans($trans_path.'email') }}</th>
                                        <th>
                                            <i class="icon-time bigger-110 hidden-480"></i>
                                            {{ trans($trans_path.'update') }}
                                        </th>
                                        <th>{{ trans($trans_path.'status') }}</th>
                                        <th class="hidden-480"> {{ trans($trans_path.'action') }}</th>

                                    </tr>
                                    </thead>

                                    <tbody>

                                    @if ($data['rows']->count() > 0)
                                        @foreach($data['rows'] as $row)
                                            <tr>
                                                <td>{{ $row->id}}</td>
                                                <td>{{ $row->full_name }}</td>
                                                <td>{{ $row->name }}</td>
                                                <td>{{ $row->email }}</td>
                                                <td>{{ $row->updated_at }}</td>
                                                <td><span class="label label-sm label-{{ $row->status == 1?'success':'warning' }}">{{ $row->status == 1?'Active':'Inactive' }}</span></td>
                                                <td>
                                                    <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                                                        <a href="{{ route('admin.users.edit', [ 'id' => $row->id ]) }}" class="btn btn-xs btn-info">
                                                            <i class="icon-edit bigger-120"></i>
                                                        </a>

                                                        <a href="{{ route('admin.users.destroy', [ 'id' => $row->id ]) }}" class="btn btn-xs btn-danger bootbox-confirm">
                                                            <i class="icon-trash bigger-120"></i>
                                                        </a>

                                                    </div>

                                                </td>
                                            </tr>
                                        @endforeach

                                    @else

                                        <tr>
                                            <td colspan="7">No data found.</td>
                                        </tr>

                                    @endif

                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <td colspan="7">
                                            {!! $data['rows']->appends($search)->render() !!}
                                        </td>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /span -->
                    </div><!-- /row -->

                    <div class="hr hr-18 dotted hr-double"></div>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div><!-- /.main-content -->

@endsection


@section('page_specific_script')

    <script>
        $(document).ready(function () {

            $('#search_btn').click(function () {

                var search_by = $('#search_by').val();
                var search_key = $('#search_key').val();

                var current_url = '{{ URL::current() }}';

                var redirect_url = current_url + '?search_by=' + search_by + '&search_key=' + search_key;
                location.href = redirect_url;

                // console.log(redirect_url);
            });


            $('#search_by').on('change', function () {
                if ($(this).val() == 'status') {
                    $('#search_by_hint').html('Possible keys are [ active / inactive ]').show();
                } else {
                    $('#search_by_hint').hide();
                }
            });


        });
    </script>

@endsection